### ISSUE TITLE
host not found error

### ISSUE THREAD

**Issue by mmarseglia** [gosddc/vagrant-vcenter#29]
Hi,
 I set vcenter.computer_name to the name of the ESXi host as it appears in vCenter but I get a "Host not found" error when I vagrant up.  The host is a cluster member and the cluster is in a folder. 

vcenter.computer_name = 'host1.corp.com'

$ vagrant up
Bringing machine 'server' up with 'vcenter' provider...
==> server: Uploading [centos-7-1-x64-vmware-ovf]...
==> server: Adding [centos-7-1-x64-vmware-ovf]
.vagrant.d/gems/gems/vagrant-vcenter-0.3.2/lib/vagrant-vcenter/action/inventory_check.rb:64:in `vcenter_upload_box': Host not found (RuntimeError)
	from .vagrant.d/gems/gems/vagrant-vcenter-0.3.2/lib/vagrant-vcenter/action/inventory_check.rb:122:in `vcenter_check_inventory'

**Comment by tsugliani** [comment]
Hi @mmarseglia,

Can you try with the name of your cluster ? (just to see if you get a different result)

**Comment by mmarseglia** [comment]
I did get this to work, I think I downloaded and compiled the development branch.
