### ISSUE TITLE
Cannot start machine using template uploaded by 0.3.2

### ISSUE THREAD

**Issue by vladistan** [gosddc/vagrant-vcenter#32]
On latest develop branch commit id d2c47a5  

When trying to ```vagrant up``` the machine using template uploaded by plugin version 0.3.2 the Vagrant fails with the message  

vCenter Provider:
* The following settings shouldn't exist: vmfolder

This message occurs regardless whether ```vcenter.folder_name``` exists in the Vagrantfile or not

**Comment by mmarseglia** [comment]
I think I found and fixed this bug.  Please see my PR.

**Comment by mmarseglia** [comment]
Can we close this? My PR was accepted and fixed this bug.

**Comment by tsugliani** [comment]
Hi @mmarseglia,

Closing now, sorry being very busy with other stuff right now :(
